"""Add email verified to user

Revision ID: f5c0e329ec4e
Revises: 58cbbc4406e1
Create Date: 2020-12-10 02:10:47.619985+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c0e329ec4e'
down_revision = '58cbbc4406e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'email_verified', 
        sa.Boolean(), 
        nullable=False,
        server_default='False'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
